language: cpp
matrix:
  include:
    - os: linux
      env: IMAGE=ubuntu:rolling COMMAND=build_linux_gcc_coverall_ubuntu
      services: docker
    - os: linux
      env: IMAGE=debian:stable COMMAND=build_linux_gcc_debian
      services: docker
    - os: linux
      env: IMAGE=fedora:latest COMMAND=build_linux_gcc_fedora
      services: docker
    - os: linux
      env: IMAGE=ubuntu:rolling COMMAND=build_linux_clang_ubuntu
      services: docker
    - os: osx
      env: IMAGE=native COMMAND=build_osx
script:
  - $TRAVIS_BUILD_DIR/test.sh ${IMAGE} ${COMMAND}
env:
  global:
    secure: J52dK8uM1haWOP5Ktz01VETiYdpyOKtnGZXcZjxEXI7RV+44/MpkSSpKFrIex1jHDodn01Tv+/otmxotaz1HOPv4DgT2gg8FbHlpvnc6+B1/dEaeCDvnd33odmARoOszP0MNFTZdlvg6zGeJwPDYFfITn1jiFBtjazu19VIbQE4D1CSKkWsMXeyH1WjTb0LEtxhYwUcFgNqDb6trArx8xlvZNrh2/j5nPgAzvmuT0JuzwcRz9swwZftKcMjaK5JooSBTydtAzgVpVMZf1q+pF0nR9VlYIY34qQLsWirBjWHGRKdkgAEEN4vEMD1BKbhkIn7TjEpWLrH3BZuJY8uXAfnxvT8KXns2fhA1EDjlP/5n2y1jXAjqCZX8o1dC2fn6qxpL1Qg1WE0n9mhOZLMpbzCpJjBumjQPPUsviggRUs4awSYv3JrYuavvXQZ9rFM634O7CLIDVmbqssVyIYMhgIqLFAWgDxTyAxt+67vUy5ONsAenMOJ6bO36pYZHWH53isCRblUD5nq6Dj6WrW9P7lQhAdhvZ+Hyt+zyVCCblDY9lAv1KetU4i9sDSNYUkQtFTPVBw8LE4JmEctuM7iC6YqeneffPzzDLsGZ70m66VT1L4MYg5h2fGbtRuQ1nPz0+k2CNibN7NegaY35d7gUosnJJF04AeOUcea4+rgQkVM=
